version: 2

defaults: &defaults
  working_directory: ~/kactus-io/kactus
  macos:
    xcode: '9.3.0'

jobs:
  build:
    <<: *defaults
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-packages-v1-{{ .Branch }}-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: node-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - vendor/bundle
            - .eslintcache
            - ~/.electron
            - ./node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build:prod
      - run:
          name: Test
          command: |
            npm run test:setup
            # npm run test
      - run:
          name: Report to codecov
          command: yarn test:report
      - run:
          name: Teardown
          command:
            find $HOME/Library/Developer/Xcode/DerivedData -name
            '*.xcactivitylog' -exec cp {} $CIRCLE_ARTIFACTS/xcactivitylog \; ||
            true
      # Save test results
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
      - persist_to_workspace:
          root: ~/kactus-io/kactus
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/kactus-io/kactus
      - run: npm run publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /^__release-.*/
